- hostname: csr1000v-1
  ip: ios-xe-mgmt-latest.cisco.com
  port: 8181
  device_type: cisco_ios
  username: developer
  password: C1sco12345

#- hostname: csr1000v-2
#  ip: ios.cisco.com
#  port: 8181
#  username: developer
#  password: C1sco12345
#  device_type: cisco_ios